<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.0">
  <POU Name="MAIN" Id="{62977ecd-ac31-43d2-8bc8-b9b1c617a583}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	bEingang:BOOL;
	sFirmaName:string;
	aArraya:ARRAY[1..80]OF BYTE;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>